fail_fast: false
default_stages: [ pre-commit, pre-push ]
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus" ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.15.0
    hooks:
      - id: reorder-python-imports
        args: [ "--application-directories", "src" ]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13.6
        args: [ "--config=pyproject.toml" ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=88" ] # Following Black's convention
        additional_dependencies:
          - flake8-bugbear==24.12.12
          - flake8-comprehensions==3.16.0
          - pep8-naming==0.11.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["types-pyyaml"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        additional_dependencies: ["@commitlint/config-conventional"]
        stages: [ commit-msg ]
