worker:
  log_level: info
  debug: true

database:
  connection_string: "postgres://test_user:password@localhost:5400/pushservice-db"

kafka:
  brokers:
    - localhost:9393
  topic: "pushservice.notifications"
  group_id: "ParserConsumerGroup"
  service_name: "ParserConsumer"

