worker:
  log_level: INFO
  debug: true

database:
  connection_string: "postgres://test_user:password@localhost:5400/pushservice_db"

kafka:
  brokers:
    - localhost:9093

web_api:
  enabled: true
  host: 'localhost'
  port: 5000

parser:
  topic: "raw-push"
  group_id: "ParserConsumerGroup"

sender:
  topic: "send-push"
  group_id: "SenderConsumerGroup"
